# Generated by Django 5.2.1 on 2025-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='email',
        ),
        migrations.AddField(
            model_name='autor',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
