# Generated by Django 5.2.1 on 2025-06-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_fecha_entrada_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
